"""Create reminders and tasks tables

Revision ID: 214ec655f6c1
Revises: f14f4c210e78
Create Date: 2023-05-27 18:29:34.857094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214ec655f6c1'
down_revision = 'f14f4c210e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    # sa.Column('start_date', sa.NullType(), nullable=True),
    # sa.Column('end_date', sa.NullType(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_is_done'), 'reminders', ['is_done'], unique=False)
    op.create_index(op.f('ix_reminders_is_visible'), 'reminders', ['is_visible'], unique=False)
    op.create_index(op.f('ix_reminders_title'), 'reminders', ['title'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    # sa.Column('start_date', sa.NullType(), nullable=True),
    # sa.Column('end_date', sa.NullType(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_visible'), 'tasks', ['is_visible'], unique=False)
    op.create_index(op.f('ix_tasks_style'), 'tasks', ['style'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_style'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_visible'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_reminders_title'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_visible'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_done'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
