"""Add star_date and end_date columns to event tables

Revision ID: 361af4bb5350
Revises: e4681405c18b
Create Date: 2023-05-27 18:36:54.883239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361af4bb5350'
down_revision = 'e4681405c18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('reminders', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_reminders_end_date'), 'reminders', ['end_date'], unique=False)
    op.create_index(op.f('ix_reminders_start_date'), 'reminders', ['start_date'], unique=False)
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_end_date'), 'tasks', ['end_date'], unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_start_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_end_date'), table_name='tasks')
    op.drop_column('tasks', 'end_date')
    op.drop_column('tasks', 'start_date')
    op.drop_index(op.f('ix_reminders_start_date'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_end_date'), table_name='reminders')
    op.drop_column('reminders', 'end_date')
    op.drop_column('reminders', 'start_date')
    # ### end Alembic commands ###
