"""Add name column to user table

Revision ID: 74a36f0ebc23
Revises: 2438d8ea7388
Create Date: 2023-06-04 13:14:41.836092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a36f0ebc23'
down_revision = '2438d8ea7388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass  # Alembic, jesus CHRIST. SIGH. SIGH!!!!!!!! (no comment elaboration necessary)
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # op.alter_column('users', 'hashed_password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass  # Alembic, jesus CHRIST. SIGH. SIGH!!!!!!!! (no comment elaboration necessary)
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'hashed_password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.drop_column('users', 'name')
    # ### end Alembic commands ###
