"""Create events (event group) table

Revision ID: f14f4c210e78
Revises: c3cf2a3ac4bc
Create Date: 2023-05-27 18:25:52.191836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14f4c210e78'
down_revision = 'c3cf2a3ac4bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('event_array', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_array'), 'events', ['event_array'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_visible'), 'events', ['is_visible'], unique=False)
    op.create_index(op.f('ix_events_style'), 'events', ['style'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_style'), table_name='events')
    op.drop_index(op.f('ix_events_is_visible'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_array'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
